name: 'Parent Images: Release'

on:
  release:
    types: [prereleased]
    
permissions:
  id-token: write
  contents: read
  actions: read

jobs: 
  call-pi-release:
    uses: code-kern-ai/cicd-deployment-scripts/.github/workflows/pi_release.yml@dev
    secrets: inherit